In [3]:
from pyspark.sql import SparkSession

In [4]:
spark = SparkSession.builder.appName("aula-pyspark").getOrCreate()

In [3]:
df = spark.read.csv('https://cursos.grandeporte.com.br/files/brq/big-data/datasets/ABT.csv',inferSchema=True,header=True)

In [4]:
type(df)

pyspark.sql.dataframe.DataFrame

In [5]:
df.printSchema()

root
 |-- date: string (nullable = true)
 |-- volume: integer (nullable = true)
 |-- open: double (nullable = true)
 |-- high: double (nullable = true)
 |-- low: double (nullable = true)
 |-- close: double (nullable = true)
 |-- adjclose: double (nullable = true)

In [6]:
df.columns

['date', 'volume', 'open', 'high', 'low', 'close', 'adjclose']

In [7]:
df.describe().show()

+-------+----------+-----------------+------------------+-------------------+-------------------+------------------+--------------------+
|summary|      date|           volume|              open|               high|                low|             close|            adjclose|
+-------+----------+-----------------+------------------+-------------------+-------------------+------------------+--------------------+
|  count|     10162|            10162|             10162|              10162|              10162|             10162|               10162|
|   mean|      null| 8275284.63885062|20.168525328002232| 20.430021807853453| 20.031556520407957| 20.24107723204059|  14.705467844034768|
| stddev|      null|5617558.864392693|19.610983488336288| 19.724258777219035|  19.36039868811152| 19.55249673470384|  19.873038154278635|
|    min|1980-03-17|           352200|               0.0|0.49098533391952515|0.47871071100234985|0.4874782860279083|0.009539752267301083|
|    max|2020-07-02|         78108300| 97.44999694824219|              100.0|   94.6500015258789|              98.0|                98.0|
+-------+----------+-----------------+------------------+-------------------+-------------------+------------------+--------------------+

In [48]:
df.filter("Close<500").show()

+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|      date|  volume|             open|             high|              low|            close|         adjclose|
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|2020-07-02| 3845300|             92.5|93.05999755859375|91.93000030517578| 92.2300033569336| 92.2300033569336|
|2020-07-01| 3389600| 91.9800033569336| 91.9800033569336|90.43000030517578|91.63999938964844|91.63999938964844|
|2020-06-30| 5220900|            88.75| 91.9000015258789|88.44000244140625|91.43000030517578|91.43000030517578|
|2020-06-29| 4669300|89.58000183105469|89.69999694824219|88.08999633789062|89.01000213623047|89.01000213623047|
|2020-06-26| 8522500|89.81999969482422|89.94999694824219|87.94000244140625|88.70999908447266|88.70999908447266|
|2020-06-25| 5781100|87.23999786376953|89.80999755859375|86.16000366210938|89.62000274658203|89.62000274658203|
|2020-06-24| 6141900|90.62999725341797| 90.7300033569336|86.81999969482422|87.30000305175781|87.30000305175781|
|2020-06-23| 4156900|91.11000061035156|92.30000305175781|90.79000091552734|91.30000305175781|91.30000305175781|
|2020-06-22| 5072800|90.33000183105469| 90.6500015258789|89.16000366210938|90.33999633789062|90.33999633789062|
|2020-06-19| 9473300|91.66999816894531| 92.4000015258789|90.61000061035156|90.68000030517578|90.68000030517578|
|2020-06-18| 6022900|             90.5|91.33999633789062|89.56999969482422|90.27999877929688|90.27999877929688|
|2020-06-17| 4359100|90.41999816894531|91.66999816894531| 90.0999984741211| 90.9000015258789| 90.9000015258789|
|2020-06-16| 6143400|90.62000274658203|91.76000213623047|89.13999938964844|89.73999786376953|89.73999786376953|
|2020-06-15| 5666000| 87.5199966430664| 90.3499984741211|87.05000305175781|89.55000305175781|89.55000305175781|
|2020-06-12| 5590400|            89.25|90.19000244140625|87.58999633789062| 89.0199966430664| 89.0199966430664|
|2020-06-11| 8168300|92.16999816894531|             92.5|86.94000244140625|87.77999877929688|87.77999877929688|
|2020-06-10| 5829100| 90.8499984741211|            92.75|90.63999938964844|92.16000366210938|92.16000366210938|
|2020-06-09| 4857400|92.31999969482422|92.81999969482422|90.23999786376953| 90.2699966430664| 90.2699966430664|
|2020-06-08| 5426800| 88.9800033569336|92.61000061035156|88.91000366210938|92.55999755859375|92.55999755859375|
|2020-06-05|11874500|88.47000122070312|89.95999908447266|87.31999969482422|89.86000061035156|89.86000061035156|
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
only showing top 20 rows

In [8]:
from pyspark.sql.functions import format_number

In [28]:
df.filter("Close<500").select('Open').show()

+------------------+
|              Open|
+------------------+
| 46.79999923706055|
| 45.16999816894531|
| 45.91999816894531|
|  45.2400016784668|
|43.470001220703125|
| 42.16999816894531|
|43.560001373291016|
| 44.54999923706055|
|42.119998931884766|
| 43.91999816894531|
| 44.02000045776367|
| 45.45000076293945|
| 46.29999923706055|
| 41.18000030517578|
|44.779998779296875|
|42.279998779296875|
|48.470001220703125|
|48.209999084472656|
|             48.25|
| 45.84000015258789|
+------------------+
only showing top 20 rows

In [9]:
dfMax = df.withColumn("max/vol",df["High"]/df["Volume"])
dfMax.select('max/vol').show()

+--------------------+
|             max/vol|
+--------------------+
|2.420097198101416E-5|
|2.713594623463936...|
|1.760232939261026E-5|
|1.921058765730242E-5|
|1.055441442631178...|
|1.553510535340917E-5|
|1.477230227729751...|
|2.220404701863355E-5|
|1.786981578731251E-5|
|9.753729062299189E-6|
|1.516545125070823...|
| 2.10295699040961E-5|
|1.493635480942645...|
| 1.59459933770069E-5|
|1.613301417455034...|
|1.132426575909307...|
|1.591154723713780...|
|1.910898828484873E-5|
|1.706530563321876E-5|
|7.575897855444243E-6|
+--------------------+
only showing top 20 rows

In [15]:
from pyspark.sql.functions import max,min

In [16]:
df.select(max("volume"),min("volume")).show()

+-----------+-----------+
|max(volume)|min(volume)|
+-----------+-----------+
|   78108300|     352200|
+-----------+-----------+

In [29]:
df.filter("Close<500").select(['Open','Close']).show()

+------------------+------------------+
|              Open|             Close|
+------------------+------------------+
| 46.79999923706055| 44.72999954223633|
| 45.16999816894531|45.290000915527344|
| 45.91999816894531|45.400001525878906|
|  45.2400016784668|              46.5|
|43.470001220703125| 44.31999969482422|
| 42.16999816894531|44.119998931884766|
|43.560001373291016| 42.77000045776367|
| 44.54999923706055|44.380001068115234|
|42.119998931884766|43.560001373291016|
| 43.91999816894531|  42.2599983215332|
| 44.02000045776367|43.380001068115234|
| 45.45000076293945|44.310001373291016|
| 46.29999923706055|              45.5|
| 41.18000030517578|43.939998626708984|
|44.779998779296875| 43.54999923706055|
|42.279998779296875| 41.97999954223633|
|48.470001220703125|45.630001068115234|
|48.209999084472656|48.470001220703125|
|             48.25|49.279998779296875|
| 45.84000015258789| 45.56999969482422|
+------------------+------------------+
only showing top 20 rows

In [11]:
df.columns

['date', 'volume', 'open', 'high', 'low', 'close', 'adjclose']

In [12]:
dfMax.columns

['date', 'volume', 'open', 'high', 'low', 'close', 'adjclose', 'max/vol']

In [9]:
df.filter(df["Close"] < 200).show()

+----------+-------+------------------+------------------+------------------+------------------+------------------+
|      date| volume|              open|              high|               low|             close|          adjclose|
+----------+-------+------------------+------------------+------------------+------------------+------------------+
|2020-07-02| 413000| 46.79999923706055| 47.41999816894531|44.540000915527344| 44.72999954223633| 44.72999954223633|
|2020-07-01| 597900| 45.16999816894531| 46.56999969482422| 44.36000061035156|45.290000915527344|45.290000915527344|
|2020-06-30| 622200| 45.91999816894531|              46.5| 45.04999923706055|45.400001525878906|45.400001525878906|
|2020-06-29| 649200|  45.2400016784668| 46.83000183105469| 44.06999969482422|              46.5|              46.5|
|2020-06-26|1885900|43.470001220703125| 44.40999984741211|42.849998474121094| 44.31999969482422| 44.31999969482422|
|2020-06-25| 528400| 42.16999816894531|  44.2400016784668|41.900001525878906|44.119998931884766|44.119998931884766|
|2020-06-24| 480200|43.560001373291016|              44.0|41.529998779296875| 42.77000045776367| 42.77000045776367|
|2020-06-23| 401700| 44.54999923706055|44.810001373291016| 43.58000183105469|44.380001068115234|44.380001068115234|
|2020-06-22| 641500|42.119998931884766| 44.31999969482422|41.189998626708984|43.560001373291016|43.560001373291016|
|2020-06-19|1400400| 43.91999816894531| 44.83000183105469| 42.20000076293945|  42.2599983215332|  42.2599983215332|
|2020-06-18| 641500| 44.02000045776367| 45.09000015258789|43.060001373291016|43.380001068115234|43.380001068115234|
|2020-06-17| 562800| 45.45000076293945| 45.45000076293945| 44.06999969482422|44.310001373291016|44.310001373291016|
|2020-06-16|1989700| 46.29999923706055| 46.38999938964844| 43.31999969482422|              45.5|45.459999084472656|
|2020-06-15| 889400| 41.18000030517578| 44.36000061035156|40.650001525878906|43.939998626708984|43.901371002197266|
|2020-06-12| 672300|44.779998779296875|  45.0099983215332| 42.09000015258789| 43.54999923706055|43.511714935302734|
|2020-06-11| 839300|42.279998779296875| 43.90999984741211|40.689998626708984| 41.97999954223633| 41.94309616088867|
|2020-06-10| 866200|48.470001220703125| 48.90999984741211| 44.84000015258789|45.630001068115234| 45.58988571166992|
|2020-06-09|1159800|48.209999084472656| 50.09000015258789| 47.06999969482422|48.470001220703125|48.427391052246094|
|2020-06-08|1617300|             48.25| 49.61000061035156|48.040000915527344|49.279998779296875| 49.23667526245117|
|2020-06-05|1279000| 45.84000015258789| 49.16999816894531| 45.11000061035156| 45.56999969482422|45.529937744140625|
+----------+-------+------------------+------------------+------------------+------------------+------------------+
only showing top 20 rows

In [17]:
from pyspark.sql.functions import year

In [10]:
col = df.filter(df["Volume"] == 1400400).collect()

[Row(date='2020-06-19', volume=1400400, open=43.91999816894531, high=44.83000183105469, low=42.20000076293945, close=42.2599983215332, adjclose=42.2599983215332)]

In [18]:
yeardf = df.withColumn("Year",year(df["Date"]))

In [23]:
yeardf.describe().show()

+-------+----------+-----------------+------------------+-------------------+-------------------+------------------+--------------------+------------------+
|summary|      date|           volume|              open|               high|                low|             close|            adjclose|              Year|
+-------+----------+-----------------+------------------+-------------------+-------------------+------------------+--------------------+------------------+
|  count|     10162|            10162|             10162|              10162|              10162|             10162|               10162|             10162|
|   mean|      null| 8275284.63885062|20.168525328002232| 20.430021807853453| 20.031556520407957| 20.24107723204059|  14.705467844034768|1999.8317260381814|
| stddev|      null|5617558.864392693|19.610983488336288| 19.724258777219035|  19.36039868811152| 19.55249673470384|  19.873038154278635|11.641244610337726|
|    min|1980-03-17|           352200|               0.0|0.49098533391952515|0.47871071100234985|0.4874782860279083|0.009539752267301083|              1980|
|    max|2020-07-02|         78108300| 97.44999694824219|              100.0|   94.6500015258789|              98.0|                98.0|              2020|
+-------+----------+-----------------+------------------+-------------------+-------------------+------------------+--------------------+------------------+

In [29]:
yeardf.select("volume","open", "year").show()

+--------+-----------------+----+
|  volume|             open|year|
+--------+-----------------+----+
| 3845300|             92.5|2020|
| 3389600| 91.9800033569336|2020|
| 5220900|            88.75|2020|
| 4669300|89.58000183105469|2020|
| 8522500|89.81999969482422|2020|
| 5781100|87.23999786376953|2020|
| 6141900|90.62999725341797|2020|
| 4156900|91.11000061035156|2020|
| 5072800|90.33000183105469|2020|
| 9473300|91.66999816894531|2020|
| 6022900|             90.5|2020|
| 4359100|90.41999816894531|2020|
| 6143400|90.62000274658203|2020|
| 5666000| 87.5199966430664|2020|
| 5590400|            89.25|2020|
| 8168300|92.16999816894531|2020|
| 5829100| 90.8499984741211|2020|
| 4857400|92.31999969482422|2020|
| 5426800| 88.9800033569336|2020|
|11874500|88.47000122070312|2020|
+--------+-----------------+----+
only showing top 20 rows

In [28]:
yeardf.limit(2).show()

+----------+-------+----------------+-----------------+-----------------+-----------------+-----------------+----+
|      date| volume|            open|             high|              low|            close|         adjclose|Year|
+----------+-------+----------------+-----------------+-----------------+-----------------+-----------------+----+
|2020-07-02|3845300|            92.5|93.05999755859375|91.93000030517578| 92.2300033569336| 92.2300033569336|2020|
|2020-07-01|3389600|91.9800033569336| 91.9800033569336|90.43000030517578|91.63999938964844|91.63999938964844|2020|
+----------+-------+----------------+-----------------+-----------------+-----------------+-----------------+----+

In [54]:
from pyspark.sql.functions import col, asc, desc
max_df = yeardf.groupBy('Year').max()
max_df.sort( col("Year").desc() ).limit(5).show()

+----+-----------+------------------+------------------+------------------+------------------+------------------+---------+
|Year|max(volume)|         max(open)|         max(high)|          max(low)|        max(close)|     max(adjclose)|max(Year)|
+----+-----------+------------------+------------------+------------------+------------------+------------------+---------+
|2020|   47540200| 97.44999694824219|             100.0|  94.6500015258789|              98.0|              98.0|     2020|
|2019|   16436700| 88.98999786376953| 89.23999786376953|  87.8499984741211| 88.73999786376953| 87.64277648925781|     2019|
|2018|   15261900| 74.29000091552734| 74.91999816894531| 73.55999755859375|  74.2699966430664|  72.4442367553711|     2018|
|2017|   22644500|57.599998474121094| 57.77000045776367|57.369998931884766|57.470001220703125|55.048362731933594|     2017|
|2016|   54527700|45.720001220703125|45.790000915527344|  44.9900016784668|45.290000915527344|  42.1301383972168|     2016|
+----+-----------+------------------+------------------+------------------+------------------+------------------+---------+

In [56]:
from pyspark.sql.functions import month
monthdf = df.withColumn("Month", month("Date"))
monthmax = monthdf.select("Month","Close").groupBy("Month").max()
monthmax.select("Month","max(Close)").orderBy('Month').show()

+-----+-----------------+
|Month|       max(Close)|
+-----+-----------------+
|    1|91.86000061035156|
|    2|89.66000366210938|
|    3|82.08999633789062|
|    4|             98.0|
|    5|96.06999969482422|
|    6|93.01000213623047|
|    7| 92.2300033569336|
|    8|86.88999938964844|
|    9|86.04000091552734|
|   10|84.01000213623047|
|   11|85.70999908447266|
|   12| 87.4000015258789|
+-----+-----------------+

In [38]:
from pyspark.sql.functions import format_number
#df.select("open", format_number( df["volume"].cast('float'),2).alias("open_float") ).show()

dfFormat = df.withColumn( "open_float", format_number( df["open"].cast('float'),2) )

dfFormat.select("open","open_float").limit(2).show()

+----------------+----------+
|            open|open_float|
+----------------+----------+
|            92.5|     92.50|
|91.9800033569336|     91.98|
+----------------+----------+

In [31]:
result = df.filter(df["Volume"] == 1400400).collect()

In [32]:
print (result)

[Row(date='2020-06-19', volume=1400400, open=43.91999816894531, high=44.83000183105469, low=42.20000076293945, close=42.2599983215332, adjclose=42.2599983215332)]

In [34]:
row = result[0]

In [36]:
type(row)

pyspark.sql.types.Row

In [13]:
row.asDict()

{'date': '2020-06-19',
 'volume': 1400400,
 'open': 43.91999816894531,
 'high': 44.83000183105469,
 'low': 42.20000076293945,
 'close': 42.2599983215332,
 'adjclose': 42.2599983215332}

In [14]:
df.groupBy("date").mean().show()

+----------+-----------+------------------+------------------+------------------+------------------+------------------+
|      date|avg(volume)|         avg(open)|         avg(high)|          avg(low)|        avg(close)|     avg(adjclose)|
+----------+-----------+------------------+------------------+------------------+------------------+------------------+
|2020-04-13|   779800.0|24.959999084472656|24.959999084472656|23.670000076293945|24.690000534057617| 24.66829490661621|
|2020-02-26|  1155300.0|43.130001068115234|43.130001068115234| 41.18000030517578|              41.5|  41.3732795715332|
|2019-08-23|   431900.0| 63.95000076293945|  64.7300033569336| 61.88999938964844| 62.13999938964844| 61.87360382080078|
|2019-08-22|   418600.0| 64.44999694824219| 65.44999694824219| 64.38999938964844| 64.52999877929688| 64.25336456298828|
|2019-08-08|   531600.0| 64.51000213623047| 65.94000244140625| 64.36000061035156| 65.47000122070312|  65.1893310546875|
|2017-12-05|   821000.0| 37.68000030517578|              38.0|37.130001068115234|  37.5099983215332| 37.17148208618164|
|2016-08-17|   462800.0|24.920000076293945|25.079999923706055|24.489999771118164|24.850000381469727|24.521100997924805|
|2015-05-01|   473100.0|34.099998474121094|34.880001068115234|34.099998474121094| 34.66999816894531| 34.06252670288086|
|2014-05-27|   457300.0|              33.0|33.150001525878906|32.790000915527344| 32.90999984741211| 32.23414611816406|
|2013-03-14|   288500.0|28.479999542236328|28.780000686645508|28.389999389648438|28.450000762939453|27.792835235595703|
|2010-09-24|    11800.0|17.850000381469727|17.899999618530273|17.559999465942383|17.899999618530273|17.388896942138672|
|2010-02-12|      600.0| 16.16666603088379| 16.16666603088379| 16.16666603088379| 16.16666603088379| 15.66734504699707|
|2009-12-04|     1500.0|14.006667137145996|14.006667137145996|14.006667137145996|14.006667137145996|13.574060440063477|
|2008-12-03|     1900.0|13.479999542236328|13.479999542236328|12.833333015441895|12.966666221618652|12.526704788208008|
|2007-09-13|      600.0|              16.0|              16.0|15.766666412353516|15.766666412353516|15.169913291931152|
|2007-03-06|     1800.0|15.666666984558105| 16.16666603088379|15.666666984558105| 16.16666603088379|15.526106834411621|
|2003-05-29|    15000.0|6.1777777671813965| 6.222222328186035|6.1777777671813965| 6.222222328186035| 5.920815944671631|
|2002-06-21|      100.0|6.7022223472595215|6.7022223472595215|6.7022223472595215|6.7022223472595215| 6.371706962585449|
|2002-05-13|     4200.0| 7.911110877990723| 7.970370292663574| 7.896296501159668| 7.970370292663574| 7.571507453918457|
|2001-11-16|     1500.0| 4.370370388031006| 4.370370388031006| 4.370370388031006| 4.370370388031006|   4.1460280418396|
+----------+-----------+------------------+------------------+------------------+------------------+------------------+
only showing top 20 rows

In [58]:
df.write.mode("overwrite").parquet("parquet/ABT.parquet")

In [59]:
parDF1=spark.read.parquet("parquet/ABT.parquet")
parDF1.createOrReplaceTempView("parquetTable")
parDF1.printSchema()
parDF1.show(truncate=False)

root
 |-- date: string (nullable = true)
 |-- volume: integer (nullable = true)
 |-- open: double (nullable = true)
 |-- high: double (nullable = true)
 |-- low: double (nullable = true)
 |-- close: double (nullable = true)
 |-- adjclose: double (nullable = true)

+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|date      |volume  |open             |high             |low              |close            |adjclose         |
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|2020-07-02|3845300 |92.5             |93.05999755859375|91.93000030517578|92.2300033569336 |92.2300033569336 |
|2020-07-01|3389600 |91.9800033569336 |91.9800033569336 |90.43000030517578|91.63999938964844|91.63999938964844|
|2020-06-30|5220900 |88.75            |91.9000015258789 |88.44000244140625|91.43000030517578|91.43000030517578|
|2020-06-29|4669300 |89.58000183105469|89.69999694824219|88.08999633789062|89.01000213623047|89.01000213623047|
|2020-06-26|8522500 |89.81999969482422|89.94999694824219|87.94000244140625|88.70999908447266|88.70999908447266|
|2020-06-25|5781100 |87.23999786376953|89.80999755859375|86.16000366210938|89.62000274658203|89.62000274658203|
|2020-06-24|6141900 |90.62999725341797|90.7300033569336 |86.81999969482422|87.30000305175781|87.30000305175781|
|2020-06-23|4156900 |91.11000061035156|92.30000305175781|90.79000091552734|91.30000305175781|91.30000305175781|
|2020-06-22|5072800 |90.33000183105469|90.6500015258789 |89.16000366210938|90.33999633789062|90.33999633789062|
|2020-06-19|9473300 |91.66999816894531|92.4000015258789 |90.61000061035156|90.68000030517578|90.68000030517578|
|2020-06-18|6022900 |90.5             |91.33999633789062|89.56999969482422|90.27999877929688|90.27999877929688|
|2020-06-17|4359100 |90.41999816894531|91.66999816894531|90.0999984741211 |90.9000015258789 |90.9000015258789 |
|2020-06-16|6143400 |90.62000274658203|91.76000213623047|89.13999938964844|89.73999786376953|89.73999786376953|
|2020-06-15|5666000 |87.5199966430664 |90.3499984741211 |87.05000305175781|89.55000305175781|89.55000305175781|
|2020-06-12|5590400 |89.25            |90.19000244140625|87.58999633789062|89.0199966430664 |89.0199966430664 |
|2020-06-11|8168300 |92.16999816894531|92.5             |86.94000244140625|87.77999877929688|87.77999877929688|
|2020-06-10|5829100 |90.8499984741211 |92.75            |90.63999938964844|92.16000366210938|92.16000366210938|
|2020-06-09|4857400 |92.31999969482422|92.81999969482422|90.23999786376953|90.2699966430664 |90.2699966430664 |
|2020-06-08|5426800 |88.9800033569336 |92.61000061035156|88.91000366210938|92.55999755859375|92.55999755859375|
|2020-06-05|11874500|88.47000122070312|89.95999908447266|87.31999969482422|89.86000061035156|89.86000061035156|
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
only showing top 20 rows

In [60]:
parDF1.show()

+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|      date|  volume|             open|             high|              low|            close|         adjclose|
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|2020-07-02| 3845300|             92.5|93.05999755859375|91.93000030517578| 92.2300033569336| 92.2300033569336|
|2020-07-01| 3389600| 91.9800033569336| 91.9800033569336|90.43000030517578|91.63999938964844|91.63999938964844|
|2020-06-30| 5220900|            88.75| 91.9000015258789|88.44000244140625|91.43000030517578|91.43000030517578|
|2020-06-29| 4669300|89.58000183105469|89.69999694824219|88.08999633789062|89.01000213623047|89.01000213623047|
|2020-06-26| 8522500|89.81999969482422|89.94999694824219|87.94000244140625|88.70999908447266|88.70999908447266|
|2020-06-25| 5781100|87.23999786376953|89.80999755859375|86.16000366210938|89.62000274658203|89.62000274658203|
|2020-06-24| 6141900|90.62999725341797| 90.7300033569336|86.81999969482422|87.30000305175781|87.30000305175781|
|2020-06-23| 4156900|91.11000061035156|92.30000305175781|90.79000091552734|91.30000305175781|91.30000305175781|
|2020-06-22| 5072800|90.33000183105469| 90.6500015258789|89.16000366210938|90.33999633789062|90.33999633789062|
|2020-06-19| 9473300|91.66999816894531| 92.4000015258789|90.61000061035156|90.68000030517578|90.68000030517578|
|2020-06-18| 6022900|             90.5|91.33999633789062|89.56999969482422|90.27999877929688|90.27999877929688|
|2020-06-17| 4359100|90.41999816894531|91.66999816894531| 90.0999984741211| 90.9000015258789| 90.9000015258789|
|2020-06-16| 6143400|90.62000274658203|91.76000213623047|89.13999938964844|89.73999786376953|89.73999786376953|
|2020-06-15| 5666000| 87.5199966430664| 90.3499984741211|87.05000305175781|89.55000305175781|89.55000305175781|
|2020-06-12| 5590400|            89.25|90.19000244140625|87.58999633789062| 89.0199966430664| 89.0199966430664|
|2020-06-11| 8168300|92.16999816894531|             92.5|86.94000244140625|87.77999877929688|87.77999877929688|
|2020-06-10| 5829100| 90.8499984741211|            92.75|90.63999938964844|92.16000366210938|92.16000366210938|
|2020-06-09| 4857400|92.31999969482422|92.81999969482422|90.23999786376953| 90.2699966430664| 90.2699966430664|
|2020-06-08| 5426800| 88.9800033569336|92.61000061035156|88.91000366210938|92.55999755859375|92.55999755859375|
|2020-06-05|11874500|88.47000122070312|89.95999908447266|87.31999969482422|89.86000061035156|89.86000061035156|
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
only showing top 20 rows

In [62]:
 from pyspark.sql import SQLContext

In [64]:
parkSQL = spark.sql("select * from ParquetTable where close >= 92 ")
parkSQL.show(truncate=False)

+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|date      |volume  |open             |high             |low              |close            |adjclose         |
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
|2020-07-02|3845300 |92.5             |93.05999755859375|91.93000030517578|92.2300033569336 |92.2300033569336 |
|2020-06-10|5829100 |90.8499984741211 |92.75            |90.63999938964844|92.16000366210938|92.16000366210938|
|2020-06-08|5426800 |88.9800033569336 |92.61000061035156|88.91000366210938|92.55999755859375|92.55999755859375|
|2020-06-02|6394100 |92.91999816894531|93.1500015258789 |91.76000213623047|92.62000274658203|92.62000274658203|
|2020-06-01|5451600 |92.94999694824219|93.95999908447266|92.04000091552734|93.01000213623047|93.01000213623047|
|2020-05-29|10141100|92.9000015258789 |95.58999633789062|90.75            |94.91999816894531|94.91999816894531|
|2020-05-28|5316300 |91.94999694824219|93.33000183105469|91.20999908447266|92.0999984741211 |92.0999984741211 |
|2020-05-13|11622500|93.2699966430664 |94.66999816894531|90.83999633789062|92.16000366210938|92.16000366210938|
|2020-05-12|5384200 |96.45999908447266|96.68000030517578|93.7300033569336 |93.80000305175781|93.80000305175781|
|2020-05-11|7236800 |93.22000122070312|96.48999786376953|93.13999938964844|96.06999969482422|96.06999969482422|
|2020-05-08|6170200 |94.83999633789062|94.94000244140625|92.9000015258789 |93.69999694824219|93.69999694824219|
|2020-05-07|7255000 |92.13999938964844|94.54000091552734|91.80999755859375|93.98999786376953|93.98999786376953|
|2020-05-05|6747900 |90.94999694824219|93.66000366210938|90.38999938964844|93.02999877929688|93.02999877929688|
|2020-04-30|7972700 |91.8499984741211 |93.7699966430664 |91.8499984741211 |92.08999633789062|92.08999633789062|
|2020-04-29|7068300 |92.08999633789062|93.05000305175781|91.06999969482422|92.27999877929688|92.27999877929688|
|2020-04-27|6838200 |95.4800033569336 |95.9000015258789 |94.0199966430664 |94.94999694824219|94.94999694824219|
|2020-04-24|9017700 |94.5             |94.58000183105469|92.77999877929688|94.05999755859375|94.05999755859375|
|2020-04-23|10567500|95.87000274658203|97.44999694824219|93.3499984741211 |93.94000244140625|93.94000244140625|
|2020-04-22|8370800 |94.27999877929688|95.9800033569336 |92.79000091552734|95.4800033569336 |95.4800033569336 |
|2020-04-21|12030300|96.0999984741211 |96.97000122070312|93.62000274658203|94.05000305175781|94.05000305175781|
+----------+--------+-----------------+-----------------+-----------------+-----------------+-----------------+
only showing top 20 rows

+---+---------------+--------------+--------------+---------------+---------+------+---------+
|SNo|ObservationDate|Province/State|Country/Region|    Last Update|Confirmed|Deaths|Recovered|
+---+---------------+--------------+--------------+---------------+---------+------+---------+
|  1|     01/22/2020|         Anhui|Mainland China|1/22/2020 17:00|      1.0|   0.0|      0.0|
|  2|     01/22/2020|       Beijing|Mainland China|1/22/2020 17:00|     14.0|   0.0|      0.0|
|  3|     01/22/2020|     Chongqing|Mainland China|1/22/2020 17:00|      6.0|   0.0|      0.0|
+---+---------------+--------------+--------------+---------------+---------+------+---------+
only showing top 3 rows